name: mapd CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  valgrind-test:
    name: Test Valgrind (Environment Check)
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y gcc make valgrind

      - name: Clean build artifacts
        run: make clean

      - name: Run Valgrind smoke test
        run: make valgrind-test

  memory-test:
    name: Test Backend (Memory Tests with Analyzer)
    runs-on: ubuntu-22.04
    needs: valgrind-test  # wait for Valgrind check to complete

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y gcc make valgrind

      - name: Clean build artifacts
        run: make clean

      - name: Build and run full memory test suite
        run: make ci


