name: Memory Wrapper CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  memory-test:
    runs-on: ubuntu-22.04 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y gcc make valgrind

    - name: Clean build artifacts
      run: make clean

    - name: Build and run test with LD_PRELOAD
      run: make test

    - name: Run test under Valgrind
      run: |
        if make expect_fail; then
          echo  Memory error NOT detected (unexpected)";
          exit 1
        else
          echo "Memory error correctly detected (expected failure)";
          exit 0
        fi

