name: mapd CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  valgrind-test:
    name: Test Valgrind (Environment Check)
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential valgrind cmake libgtk-4-dev pkg-config

      - name: Configure with CMake
        run: cmake -S . -B build

      - name: Build targets
        run: cmake --build build

      - name: Run Valgrind smoke test
        run: cmake --build build --target valgrind-test

  memory-test:
    name: Test Backend (Memory Tests with Analyzer)
    runs-on: ubuntu-22.04
    needs: valgrind-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential valgrind cmake libgtk-4-dev pkg-config

      - name: Configure with CMake
        run: cmake -S . -B build

      - name: Build targets
        run: cmake --build build

      - name: Run Analyzer memory test
        run: cmake --build build --target valgrind-analyzer
